### ISSUE TITLE
inkonsequente Ortsnamen

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/schnitzler-briefe-data#3]
Beim Aktualisieren des ARCHE-Imports bin ich, ist der ARCHE-Doorkeeper über folgende Probleme bei Ortsnamen gestoßen:

```ttl
<https://sws.geonames.org/3170336/> a acdh:Place ;
    acdh:hasTitle "Pompei"@de,
        "Pompeji"@de ;
    acdh:hasUrl "https://schnitzler-briefe.acdh.oeaw.ac.at/pmb1283.html" .
```

sowie 

```ttl
<https://sws.geonames.org/2911522/> a acdh:Place ;
    acdh:hasTitle "Halle (Saale)"@de,
        "Halle an der Saale"@de ;
    acdh:hasUrl "https://schnitzler-briefe.acdh.oeaw.ac.at/pmb140.html" .
```

das bedeutet, dass in den back elementen einmal 
`<placeName>Pompeji</placeName>` (L00391.xml, L03440.xml) steht, und dann wieder `<placeName>Pompei</placeName>` (in acht Dokumenten, u.a. in L00170.xml

könnte das ggf harmonisiert werden?

(es gibt auch eine geonames url `https://www.geonames.org/Piräus:`; die hab ich mittlerweile aber aus der PMB gelöscht )

**Comment by martinantonmueller** [comment]
Lieber Doorkeeper (ist das wie der Schlüsselmeister in Ghostbusters 2?) – alle Probleme dürften behoben sein. Was Du alles merkst!
